---
- name: "PLAY 1: Configure device interfaces accoridng to hostvars"
  hosts: device_roles_router
  tasks:
    - name: "TASK 1: Configure devices with interface template"
      ios_config:
        src: "../templates/interface.j2"
        save_when: changed
      notify: config_changed

  handlers:
    - name: "HANDLER 1: Display devices that were modified"
      listen: config_changed
      debug:
        msg: "{{ cli_result.commands }}"