---
- name: Play #1 - execute show version across platforms
  hosts: device_roles_router

  tasks:
    - name: “IOS - Execute show version"
      ios_command:
        commands: "show version | i Version"
      register: output

    - name: print output
      debug:
        var: output.stdout_lines[0]

